### ISSUE TITLE
tell gem-uninstall to ignore default gems / supress warnings

### ISSUE THREAD

**Issue by jbernsie** [jbernsie/rbenv-clean#3]
I would like to find a way to tell the `gem uninstall` command to ignore default gems and there fore suppress the `cannot be uninstalled because it is a default gem` warnings

**Comment by buntine** [comment]
Something like this may help:

`default_gems = Gem::Specification.reject { |g| !g.default_gem? }.map(&:name)`

That should give you an array of the default gems installed on the users current Ruby. You can use that as a blacklist (e.g "uninstall everything except these").

**Comment by buntine** [comment]
Oh, I just realised this is a bash script. OK, perhaps a whitelist is better. You could replace your `list` variable with the following, which will build a bash array with the non-default gems only:

```
list=(`ruby -e 'puts Gem::Specification.reject(&:default_gem?).map(&:name).join(" ")'`)
```

And then iterate over them with:
```
for gem in ${list[*]}; do
  # Uninstall here.
  echo ${gem}
done
```

**Comment by jbernsie** [comment]
that seems to have done it, thanks heaps @buntine :smile:
